version: "3.8"
services:
  database:
    image: mysql:8.0.20
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: VTdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_file:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 20

  client:
    build: ./projVineTracker/frontend
    ports:
      - 3030:3030
    volumes:
      - ./projVineTracker/frontend:/app
      - /app/node_modules

volumes:
  db_file: