version: "3.8"
services:
  database:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: VTdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_file:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 20
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 5s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - backend
  
  app:
    depends_on:
      - database
    build: ./projVineTracker/backend/vineTrack
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://database:3306/VTdb?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "root",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    stdin_open: true
    tty: true
    volumes:
      - ./projVineTracker/backend/vineTrack:/vineTrack
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - app
    build: ./projVineTracker/frontend
    ports:
      - 3030:3030
    volumes:
      - ./projVineTracker/frontend:/app
      - /app/node_modules
    networks:
      - frontend

  generator:
    build: ./projVineTracker/dataGenerator
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - backend

volumes:
  db_file:

networks:
  backend:
  frontend: